"""add_document_sequences_and_sales_returns

Revision ID: 8a00f86930c4
Revises: 8ad7fa5d6efa
Create Date: 2026-09-08 14:28:37.477086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a00f86930c4'
down_revision = '8ad7fa5d6efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'business_date', name='uq_document_sequences_type_date')
    )
    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sequences_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sequences_document_type'), ['document_type'], unique=False)

    op.create_table('sale_returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_number', sa.String(length=100), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('refund_method', sa.String(length=30), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("refund_method IN ('CASH', 'GCASH', 'CARD')", name='ck_sale_returns_refund_method'),
    sa.CheckConstraint("status = 'COMPLETED'", name='ck_sale_returns_status'),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_sale_returns_reason_not_empty'),
    sa.CheckConstraint('length(trim(return_number)) > 0', name='ck_sale_returns_return_number_not_empty'),
    sa.CheckConstraint('refund_amount >= 0', name='ck_sale_returns_refund_amount_non_negative'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_returns_processed_by'), ['processed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_returns_return_number'), ['return_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_returns_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sale_return_items_quantity_positive'),
    sa.CheckConstraint('refund_subtotal >= 0', name='ck_sale_return_items_refund_subtotal_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sale_return_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_return_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_items_sale_item_id'), ['sale_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_items_sale_return_id'), ['sale_return_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_return_items_sale_return_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_items_sale_item_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_items_product_id'))

    op.drop_table('sale_return_items')
    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_returns_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_returns_return_number'))
        batch_op.drop_index(batch_op.f('ix_sale_returns_processed_by'))

    op.drop_table('sale_returns')
    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sequences_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_sequences_business_date'))

    op.drop_table('document_sequences')
    # ### end Alembic commands ###
